package br.com.sistemaPlanoSaude.model.enums;


public enum Especialidades {
    
    CARDIOLOGIA,
    DERMATOLOGIA,
    PEDIATRIA,
    ORTOPEDIA,
    GINECOLOGIA,
    OBSTETRICIA,
    NEUROLOGIA,
    PSIQUIATRIA,
    OFTALMOLOGIA,
    UROLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    HEMATOLOGIA,
    ONCOLOGIA,
    PNEUMOLOGIA,
    REUMATOLOGIA,
    NEFROLOGIA,
    INFECTOLOGIA,
    OTORRINOLARINGOLOGIA,
    ANESTESIOLOGIA,
    RADIOLOGIA,
    MEDICINA_DO_TRABALHO,
    MEDICINA_ESPORTIVA,
    CIRURGIA_GERAL,
    CIRURGIA_PLASTICA,
    CIRURGIA_CARDIOVASCULAR,
    GERIATRIA,
    NUTROLOGIA,
    ALERGIA_IMUNOLOGIA,
    MEDICINA_INTENSIVA
}